apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    hint: "Distributed-computing-is-easy"
  name: noted
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
