apiVersion: batch/v1
kind: Job
metadata:
  name: musing_shaw
spec:
  parallelism: 5
  completions: 30
  template:
    metadata:
      labels:
        task: job
    spec:
      containers:
      - name: musing-shaw
        image: busybox
        command: ["echo",  "Getting ready for CKA"]
      restartPolicy: Never

