apiVersion: v1
kind: Pod
metadata:
  name: kucc4
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
  - name: redis
    image: redis
  - name: memcached
    image: memcached
  - name: consul
    image: consul
