apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-via-env
  labels:
     tasks: secret
     type: env
spec:
  containers:
  - name: redis
    image: redis
    env:
    - name: CONFIDENTIAL
      valueFrom:
        secretKeyRef:
          name: super-secret
          key: username
