apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-via-file
  labels:
     tasks: secret
     type: file
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: secret
      mountPath: "/secrets"
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: super-secret
