apiVersion: v1
kind: Pod
metadata:
  name: non-persistent-redis
  namespace: pre-prod
  labels:
     tasks: non-persistent
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: cache-control
      mountPath: /data/redis
  volumes:
  - name: cache-control
    emptyDir: {}
      
