apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-config
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /srv/app-config
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
