apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /srv/app-data
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
