apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-kusc00201
  labels:
    app: ds00201
spec:
  selector:
    matchLabels:
      app: ds00201
      task: ds
      scope: worker
  template:
    metadata:
      labels:
        app: ds00201
        task: ds
        scope: worker
    spec:
      containers:
      - name: nginx
        image: nginx
