apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds.kusc00202 
  labels:
    app: ds00202
spec:
  selector:
    matchLabels:
      app: ds00202
  template:
    metadata:
      labels:
        app: ds00202
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx
