apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ReplicationController","metadata":{"annotations":{},"name":"guestbook","namespace":"default"},"spec":{"replicas":1,"selector":{"app":"nginx"},"template":{"metadata":{"labels":{"app":"nginx"},"name":"nginx"},"spec":{"containers":[{"image":"nginx","name":"nginx","ports":[{"containerPort":80}]}]}}}}
    creationTimestamp: "2020-06-15T06:26:30Z"
    generation: 2
    labels:
      app: nginx
    name: guestbook
    namespace: default
    resourceVersion: "18349876"
    selfLink: /api/v1/namespaces/default/replicationcontrollers/guestbook
    uid: baed92ef-4a38-49ee-b71f-6b6f4b1ef8d6
  spec:
    replicas: 3
    selector:
      app: nginx
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx
        name: nginx
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    fullyLabeledReplicas: 3
    observedGeneration: 2
    readyReplicas: 3
    replicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
